### PR TITLE
Add photos from Pear Deck meetup at Film Scene, 2015-10-21

### PR DESCRIPTION
**Pull request by nateroling**
Licensing info included, feel free to use them on the site or anywhere else you need them. Don't sweat the attribution bit, that's just part of the license, I'm not worried about it.

### CODE REVIEW

**Comment by benjaminoakes** [comment]
Awesome, thanks!

Any thoughts on using the existing license (see `LICENSE`)?  It's MIT.  Probably a bit easier to have a single license for the entire repo.

**Comment by nateroling** [comment]
Interesting question, let me get back to you. I use MIT for code, hadn't
considered it for photography!

**Comment by nateroling** [comment]
Done.

**Comment by benjaminoakes** [comment]
Thanks!

**Pull request merged**
