### PR TITLE
Use better secondary color for navigation

### PR DESCRIPTION
**Pull request by sundus-y**

### CODE REVIEW

**Comment by benjaminoakes** [comment]
Thanks!  Any chance it would be easy to get a screenshot?  (I'm pretty likely to merge, but I keep getting distracted from running this locally.)

Also, it looks like `linkchecker` is having issues.  Looks like we need to downgrade it (force an older version) or upgrade `python`.  Want to take a look at fixing?  Or should we make a separate issue, since I'm pretty sure your change wouldn't have broken any filenames...

**Comment by sundus-y** [comment]
screen shot 2016-07-01 at 1 50 49 pm

**Comment by sundus-y** [comment]
I am not sure what exactly to do with the `linkchecker` but I will try to take a look.

**Comment by benjaminoakes** [comment]
I fixed [the build](https://travis-ci.org/techcorridorio/techcorridorio.github.io/builds/144803403).  Could you update this branch please?

**Comment by benjaminoakes** [comment]
Sorry, I had no idea you pushed new changes!  Merging...

**Pull request merged**
